config/routes.rb
Rails.application.routes.draw do
  resources :timed_forms
  root 'timed_forms#index'

end

app/models/timed_form.rb
class TimedForm < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/timed_forms_controller.rb
class TimedFormsController < ApplicationController
  before_action :set_timed_form, only: [:show, :edit, :update, :destroy]

  # GET /timed_forms
  # GET /timed_forms.json
  def index
    @timed_forms = TimedForm.all
  end

  # GET /timed_forms/1
  # GET /timed_forms/1.json
  def show
    @begin = @timed_form.begin
    @countdown_remaining = @timed_form.begin
    
    a = @begin.split(":")
    @minutes = a[0].to_i
    @seconds= a[1].to_i
    @time_seconds = -(@minutes * 60 + @seconds) + 600
    @time_format = Time.at(@time_seconds).utc.strftime("%M:%S")
  end

  # GET /timed_forms/new
  def new
    @timed_form = TimedForm.new
  end

  # GET /timed_forms/1/edit
  def edit
  end

  # POST /timed_forms
  # POST /timed_forms.json
  def create
    @timed_form = TimedForm.new(timed_form_params)

    respond_to do |format|
      if @timed_form.save
        format.html { redirect_to @timed_form, notice: 'Timed form was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /timed_forms/1
  # PATCH/PUT /timed_forms/1.json
  def update
    respond_to do |format|
      if @timed_form.update(timed_form_params)
        format.html { redirect_to @timed_form, notice: 'Timed form was successfully updated.' }
        format.json { render :show, status: :ok, location: @timed_form }
      else
        format.html { render :edit }
        format.json { render json: @timed_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timed_forms/1
  # DELETE /timed_forms/1.json
  def destroy
    @timed_form.destroy
    respond_to do |format|
      format.html { redirect_to timed_forms_url, notice: 'Timed form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timed_form
      @timed_form = TimedForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timed_form_params
      params.require(:timed_form).permit(:begin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/timed_forms_helper.rb
module TimedFormsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timedform</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/timed_forms/_form.html.erb
<%= form_for(@timed_form) do |f| %>
  <% if @timed_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timed_form.errors.count, "error") %> prohibited this timed_form from being saved:</h2>

      <ul>
      <% @timed_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :begin, :class => "beginclass" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/timed_forms/edit.html.erb
<h1>Editing timed_form</h1>

<%= render 'form' %>

<%= link_to 'Show', @timed_form %> |
<%= link_to 'Back', timed_forms_path %>

app/views/timed_forms/index.html.erb
<h1>10 Minute Timed Form</h1>

<table class = "list">
  <thead>
    <tr>
      <th>List of Times</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timed_forms.each do |timed_form| %>
      <tr>
        <td><%= timed_form.begin %></td>
        <td><%= link_to 'Show', timed_form %></td>
        <td><%= link_to 'Destroy', timed_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timed form', new_timed_form_path %>

app/views/timed_forms/new.html.erb
<h1>New timed form</h1>
<div id="ten-countdown"></div><br>
<%= render 'form' %>

<%= link_to 'Back', timed_forms_path %>

<script>
  $( document ).ready(function() {
    function countdown( elementName, minutes, seconds )
{
    var element, endTime, hours, mins, msLeft, time;

    function twoDigits( n )
    {
        return (n <= 9 ? "0" + n : n);
    }

    function updateTimer()
    {
        msLeft = endTime - (+new Date);
        if ( msLeft < 1000 ) {
            element.innerHTML = "00:00";
        } else {
            time = new Date( msLeft );
            hours = time.getUTCHours();
            mins = time.getUTCMinutes();
            element.innerHTML = (hours ? hours + ':' + twoDigits( mins ) : mins) + ':' + twoDigits( time.getUTCSeconds() );
            setTimeout( updateTimer, time.getUTCMilliseconds() + 500 );
        }
    }

    element = document.getElementById( elementName );
    endTime = (+new Date) + 1000 * (60*minutes + seconds) + 500;
    updateTimer();
}

countdown( "ten-countdown", 10, 0 );

    
    
  });
</script>

app/views/timed_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recorded time (from countdown):</strong>
  <%= @timed_form.begin %>
</p>

<p class="displaytime">
  This is the remaining time: <%= @countdown_remaining %>
</p>
<p class="minutes">
  Remaining minutes: <%= @minutes %>
</p>

<p class="seconds">
  Remaining seconds: <%= @seconds %>
</p>

<p class="time_completed_seconds">
  This is the amount it took in seconds: <%= @time_seconds %>
</p>

<p class="converted_format">
  This the converted format: <%= @time_format %>
</p>

<%= link_to 'Back', timed_forms_path %>